# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'qiitaApiApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for qiitaApiApp

  target 'qiitaApiAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'qiitaApiAppUITests' do
    # Pods for testing
  end

pod 'Alamofire', '~> 5.2'
end
